language:
  - cpp
  - python
python:
  - "2.7"
compiler:
  - gcc
before_install:
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu precise main" > /etc/apt/sources.list.d/ros-latest.list'
  - wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y python-catkin-pkg python-rosdep ros-hydro-catkin
  - sudo rosdep init
  - rosdep update
  - rosdep install --from-paths . --ignore-src --rosdistro hydro -y > /dev/null
  - export CMAKE_ARGS="-DENABLE_TESTS:BOOL=True"
install:
  # Set up non-catkin build
  #- pushd .
  #- mkdir build_non_catkin
  #- cd build_non_catkin
  #- mkdir -p orocos_kdl python_orocos_kdl

  # First build without catkin
  #- pushd . && cd orocos_kdl && cmake ../../orocos_kdl $CMAKE_ARGS && sudo make all install && popd
  #- pushd . && cd python_orocos_kdl && cmake ../../python_orocos_kdl && sudo make all install && popd
  
  # Uninstall without catkin
  #- popd

  # Second, build with catkin
  - source /opt/ros/hydro/setup.bash
  - catkin_make_isolated --install --source . -j1 --cmake-args $CMAKE_ARGS 

script:
  # Run tests
  - pushd . && cd build_isolated/orocos_kdl && make check && popd
